export default [
  {
    id: "1",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/1.png",
  },
  {
    id: "2",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/2.png",
  },
  {
    id: "3",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/3.png",
  },
  {
    id: "4",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/4.png",
  },
  {
    id: "5",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/5.png",
  },
  {
    id: "6",
    title: "Malto House",
    bedroom: "4",
    shower: "2",
    number: "2",
    image: "/images/6.png",
  },
];
